BEGIN;
ALTER TABLE public.v3_customer_accounts DISABLE TRIGGER v3_customer_accounts_domain_collision;
UPDATE public.v3_customer_accounts SET domains = ARRAY(SELECT DISTINCT lower(x) FROM unnest(domains || ARRAY['anagaming.com.br','cactuscorporation.com']::text[]) x) WHERE account_key = 'Cactus Gaming';
UPDATE public.v3_customer_accounts SET account_key='harvard_business_school', label='Harvard Business School', domains=ARRAY['hbs.edu','hbsstg.org','mba2025.hbs.edu','mba2025stg.hbsstg.org','mba2026.hbs.edu','mba2026stg.hbsstg.org','mba2027.hbs.edu','mba2027stg.hbsstg.org','mba2028.hbs.edu','mba2028stg.hbsstg.org','mba2029.hbs.edu','mba2029stg.hbsstg.org','public.hbs.edu']::text[] WHERE account_key='Harvard Business School';
UPDATE public.v3_customer_accounts SET account_key='microsoft_innovation_hub', label='Microsoft Innovation Hub', domains=ARRAY['microsoft.com','ntdev.microsoft.com']::text[] WHERE account_key='microsoft';
UPDATE public.v3_customer_accounts SET account_key='nexer', label='Nexer', domains=ARRAY['nexergroup.com']::text[] WHERE account_key='Nexer Group';
UPDATE public.v3_customer_accounts SET account_key='oxy', label='Oxy', domains=ARRAY['oxy.com']::text[] WHERE account_key='Oxy';
UPDATE public.v3_customer_accounts SET account_key='sap_se', label='SAP SE', domains=ARRAY['sap.com']::text[] WHERE account_key='sap';
UPDATE public.v3_customer_accounts SET account_key='superbid_exchange', label='Superbid Exchange', domains=ARRAY['autoarremate.com','autoarremate.com.br','brmadvogados.adv.br','sbwebservices.net','sbwebservicesext.net','sold.com.br','superbid.net']::text[] WHERE account_key='Superbid';
INSERT INTO public.v3_customer_accounts (account_key, label, domains) VALUES
('3_sverige', '3 Sverige', ARRAY['tre.se']::text[]),
('50hertz', '50Hertz', ARRAY['50hertz.com','belgrid.net','elia.be']::text[]),
('abu_dhabi_ports', 'Abu Dhabi Ports', ARRAY['adports.ae']::text[]),
('adidas', 'Adidas', ARRAY['adidas-group.com','adidas.com']::text[]),
('alixio_group', 'Alixio Group', ARRAY['alixiasupport.fr','alixio.ch','alixio.com','alixio.fr','alixiochange.fr','alixiogroup.com','alixiomobilite.fr','groupealixia.fr','paradoxes-conseil.com','qurieux.fr','verbateam.com','x-pm.com']::text[]),
('alkami', 'Alkami', ARRAY['alkami.com']::text[]),
('allegis_group', 'Allegis Group', ARRAY['allegisgroup.com']::text[]),
('amadeus', 'Amadeus', ARRAY['amadeus.com']::text[]),
('american_credit_acceptance', 'American Credit Acceptance', ARRAY['acacceptance.com']::text[]),
('amgen', 'Amgen', ARRAY['amgen.com']::text[]),
('angelini_ventures', 'Angelini Ventures', ARRAY['angeliniventures.com']::text[]),
('anthos_capital', 'Anthos Capital', ARRAY['anthoscapital.com']::text[]),
('argano', 'Argano', ARRAY['argano.com']::text[]),
('articulate', 'Articulate', ARRAY['articulate.com']::text[]),
('asana', 'Asana', ARRAY['asana.com']::text[]),
('asos', 'ASOS', ARRAY['asos.com']::text[]),
('att', 'AT&T', ARRAY['att.com','atttest.com','atttest.onmicrosoft.com','cricketwireless.com','exo.att.com','intl.att.com']::text[]),
('att_courtavenue', 'AT&T - CourtAvenue', ARRAY['courtavenue.com']::text[]),
('att_frog', 'AT&T - Frog', ARRAY['att.com','frog.co']::text[]),
('atnorth', 'atNorth', ARRAY['atnorth.com','partners.atnorth.com']::text[]),
('auger', 'Auger', ARRAY['auger.com']::text[]),
('aurora', 'Aurora', ARRAY['aurora.tech']::text[]),
('autodesk', 'Autodesk', ARRAY['autodesk.com']::text[]),
('bcg', 'BCG', ARRAY['bcg.com','bcgfed.com','bcgplatinion.com']::text[]),
('beast', 'Beast', ARRAY['mrbeastyoutube.com']::text[]),
('bernoulli_educacao', 'Bernoulli Educação', ARRAY['bernoulli.com.br']::text[]),
('beyond_company', 'Beyond Company', ARRAY['beyondcompany.com.br']::text[]),
('billtrust', 'Billtrust', ARRAY['billtrust.com']::text[]),
('bitkub', 'Bitkub', ARRAY['bitkub.com']::text[]),
('boehringer_ingelheim', 'Boehringer Ingelheim', ARRAY['boehringer-ingelheim.com']::text[]),
('bosch_brazil', 'Bosch Brazil', ARRAY['br.bosch.com']::text[]),
('bosch_nordic', 'Bosch Nordic', ARRAY['de.bosch.com']::text[]),
('broadvoice', 'Broadvoice', ARRAY['broadvoice.com']::text[]),
('brookfield', 'Brookfield', ARRAY['brookfield.com','brookfieldproperties.com']::text[]),
('bse_hype', 'BSE Hype', ARRAY['hype.it','sella.it']::text[]),
('bts', 'BTS', ARRAY['bts.com']::text[]),
('buildertrend', 'Buildertrend', ARRAY['buildertrend.com']::text[]),
('cars_commerce_canada', 'Cars Commerce Canada', ARRAY['cars.com','carscommerce.inc']::text[]),
('cars_commerce_us', 'Cars Commerce US', ARRAY['accu-trade.com','cars.com','carscommerce.inc','dealerinspire.com','dealerrater.com']::text[]),
('cast_crew', 'Cast & Crew', ARRAY['castandcrew.com','theteamcompanies.com']::text[]),
('checkr', 'Checkr', ARRAY['checkr.com','ext.checkr.com']::text[]),
('citizens_financial_group', 'Citizens Financial Group', ARRAY['citizensbank.com','citizensprivatebank.com','citizenssecurities.com']::text[]),
('coexpan', 'Coexpan', ARRAY['coexpan.com']::text[]),
('cohesity', 'Cohesity', ARRAY['cohesity.com']::text[]),
('compass_group', 'Compass Group', ARRAY['compass-group.de','compass-usa.com','compassdigital.io']::text[]),
('comptia', 'CompTIA', ARRAY['comptia.org']::text[]),
('coop_bank', 'Coop Bank', ARRAY['coopbank.dk']::text[]),
('copado', 'Copado', ARRAY['copado.com']::text[]),
('creandum', 'Creandum', ARRAY['creandum.com']::text[]),
('crowdstrike', 'CrowdStrike', ARRAY['cloudstrike.com']::text[]),
('crowdstrike_ceo', 'CrowdStrike - CEO', ARRAY['crowdstrike.com']::text[]),
('databricks', 'Databricks', ARRAY['databricks.com']::text[]),
('dayforce', 'Dayforce', ARRAY['dayforce.com']::text[]),
('delaware_consulting', 'Delaware Consulting', ARRAY['delaware.co.uk','delaware.pro','delawareconsulting.com']::text[]),
('deloitte', 'Deloitte', ARRAY['deloitte.ch','deloitte.co.uk','deloitte.com','deloitte.dk','deloitte.ie']::text[]),
('deutsche_telekom', 'Deutsche Telekom', ARRAY['agv-comunity.de','businesspartner.t-mobile.at','buyin.pro','comfortcharge.de','congstar.net','detecon.com','detecon.de','eu.telekom.com','external.agv-comunity.de','external.itenos.de','external.o-s.de','external.pasm.de','external.sds.at','external.t-mobile.at','external.t-mobile.pl','external.t-systems.com','external.telekom.com','external.telekom.de','gedas.de','itenos.de','lovable.dev','magenta.at','o-s.de','open-telekom-cloud.com','orbit.de','ote.gr','pasm.de','sds.at','st3-telekom.de','st4-telekom.de','t-mobile.cz','t-mobile.pl','t-systems.com','t.ht.hr','telekom-digital.com','telekom.com','telekom.de','telekom.hu','telekom.mk','telekom.sk','vivento-cs.de']::text[]),
('distart', 'Distart', ARRAY['distart.de']::text[]),
('docway', 'Docway', ARRAY['docway.co']::text[]),
('doubleverify', 'DoubleVerify', ARRAY['doubleverify.com']::text[]),
('dzyne', 'Dzyne', ARRAY['dzyne.com']::text[]),
('eab', 'EAB', ARRAY['eab.com']::text[]),
('ehs', 'EHS', ARRAY['ehs.com']::text[]),
('elevenlabs', 'ElevenLabs', ARRAY['elevenlabs.io']::text[]),
('ellis_porter_plc', 'Ellis Porter PLC', ARRAY['ellisporter.com']::text[]),
('ema', 'Ema', ARRAY['ema.co']::text[]),
('empreendimentos_pague_menos_sa', 'Empreendimentos Pague Menos SA', ARRAY['pmenos.com.br']::text[]),
('endeavour_energy_llc', 'Endeavour Energy LLC', ARRAY['edgedenergy.com','edgedinfrastructure.com','endeavourii.com','gigagrid.com','gridblock.com','thermalworks.com']::text[]),
('entry', 'Entry', ARRAY['govassist.com']::text[]),
('eqt_group', 'EQT Group', ARRAY['eqtpartners.com']::text[]),
('ericsson', 'Ericsson', ARRAY['ericsson.com']::text[]),
('exactera', 'Exactera', ARRAY['exactera.com']::text[]),
('exp_realty', 'eXp Realty', ARRAY['exprealty.net']::text[]),
('experian', 'Experian', ARRAY['br.experian.com','experian.com']::text[]),
('extreme_digital_solutions', 'Extreme Digital Solutions', ARRAY['extreme.digital','extremegroup.app']::text[]),
('fabege', 'Fabege', ARRAY['fabege.se']::text[]),
('fanduel', 'FanDuel', ARRAY['fanduel.com']::text[]),
('first_abu_dhabi_bank', 'First Abu Dhabi Bank', ARRAY['bankfab.com']::text[]),
('first_team', 'First Team', ARRAY['firstteam.com']::text[]),
('food_folk', 'Food Folk', ARRAY['se.mcd.com']::text[]),
('frontlineed', 'FrontlineEd', ARRAY['frontlineed.com']::text[]),
('gartner', 'Gartner', ARRAY['gidealabs.onmicrosoft.com']::text[]),
('getyourguide', 'GetYourGuide', ARRAY['getyourguide.com']::text[]),
('greenstep', 'Greenstep', ARRAY['greenstep.com','greenstep.fi']::text[]),
('grid_alternatives', 'GRID Alternatives', ARRAY['gridalternatives.org']::text[]),
('grupo_energisa', 'Grupo Energisa', ARRAY['energisa.com.br']::text[]),
('gsk', 'GSK', ARRAY['gsk.com']::text[]),
('handshake', 'Handshake', ARRAY['joinhandshake.com']::text[]),
('harvard_business_publishing', 'Harvard Business Publishing', ARRAY['harvardbusiness.org','hbr.org','hbsp.harvard.edu']::text[]),
('hca_healthcare', 'HCA Healthcare', ARRAY['hcahealthcare.com']::text[]),
('hearst', 'Hearst', ARRAY['aso.com','austinhomemag.com','austinmonthly.com','bayareaps.com','beaumontenterprise.com','blackbook.com','campsystems.eu','campsystems.uk','canadianblackbook.com','cds-global.com','cdsglobal.co.uk','chron.com','contractor.hearst.it','ctpost.com','edwpub.net','elleuk.com','esquire.co.uk','express-news.net','fdbvela.com','greenwichtime.com','harpersbazaar.co.uk','hchron.com','hcnonline.com','hearst.ch','hearst.co.uk','hearst.com','hearst.es','hearst.it','hearst.nl','hearstaustinmedia.com','hearstautos.com','hearstcorp.com','hearstdigitalnews.com','hearstfdn.org','hearstmediact.com','hearstmediaservices.com','hearstnetworks.com','hearstnp.com','hearststorystudio.com','hmpg.com','houstonchronicle.com','icrossing.co.uk','icrossing.com','insidesoap.co.uk','jan-magazine.nl','journalinquirer.com','kubra.com','lmtonline.com','localedge.com','magazinepubservices.com','mdn.net','menshealth.co.uk','mhk.com','myjournalcourier.com','mysa.com','newstimes.com','pioneergroup.com','quest.nl','quotenet.nl','rw.co.uk','sanantoniomag.com','scni.com','sfchronicle.com','sfgate.com','stamfordadvocate.com','statesman.com','thetelegraph.com','timesunion.com','verylocal.com','wisn.com','wvtm.com','yourdigitalsupportteam.com']::text[]),
('hearst_camp_systems', 'Hearst - CAMP Systems', ARRAY['amstatcorp.com','avinode.com','campaviate.com','campsoftwareinc.com','campsystems.com','componentcontrol.com','corridor.aero','flightbridge.com','ilsmart.com','totalfbo.com']::text[]),
('hearst_fdb_health', 'Hearst - FDB Health', ARRAY['fdbhealth.com']::text[]),
('hearst_hchb', 'Hearst - HCHB', ARRAY['hchb.com']::text[]),
('hearst_mcg', 'Hearst - MCG', ARRAY['mcg.com']::text[]),
('hearst_motor', 'Hearst - Motor', ARRAY['motor.com']::text[]),
('hearst_noregon', 'Hearst - Noregon', ARRAY['noregon.com']::text[]),
('hearst_zynx_health', 'Hearst - Zynx Health', ARRAY['zynx.com']::text[]),
('hubspot', 'HubSpot', ARRAY['hubspot.com']::text[]),
('huel', 'Huel', ARRAY['huel.com']::text[]),
('hult_international_business_school', 'Hult International Business School', ARRAY['hult.edu']::text[]),
('ie_university', 'IE University', ARRAY['alumni.ie.edu','faculty.ie.edu','ie.edu','student.ie.edu']::text[]),
('ijility', 'iJility', ARRAY['ijility.com']::text[]),
('inkind', 'inKind', ARRAY['inkind.com']::text[]),
('inmar', 'Inmar', ARRAY['inmar.com']::text[]),
('inspired_thinking', 'Inspired Thinking', ARRAY['inspiredthinking.group','storyteq.com']::text[]),
('integrity_next', 'Integrity Next', ARRAY['integritynext.com']::text[]),
('intuit', 'Intuit', ARRAY['creditkarma.com','intuit.com']::text[]),
('ironclad', 'Ironclad', ARRAY['ironcladhq.com']::text[]),
('jll', 'JLL', ARRAY['jll.com','lasalle.com']::text[]),
('kaseya', 'Kaseya', ARRAY['datto.com','itglue.com','kaseya.com']::text[]),
('keurig_dr_pepper', 'Keurig Dr Pepper', ARRAY['kdrp.com']::text[]),
('kiefer_system_group', 'Kiefer System Group', ARRAY['kiefersystemgroup.se']::text[]),
('kivra', 'Kivra', ARRAY['kivra.com']::text[]),
('knight_frank_australia', 'Knight Frank Australia', ARRAY['au.knightfrank.com']::text[]),
('kpmg', 'KPMG', ARRAY['kpmg.com']::text[]),
('kpmg_australia', 'KPMG Australia', ARRAY['kpmg.com.au']::text[]),
('kpmg_luxembourg', 'KPMG Luxembourg', ARRAY['kpmg.lu']::text[]),
('kpmg_sweden', 'KPMG Sweden', ARRAY['kpmg.se']::text[]),
('kpmg_uk', 'KPMG UK', ARRAY['kpmg.co.uk']::text[]),
('kyndryl', 'Kyndryl', ARRAY['kyndryl.com']::text[]),
('launchdarkly', 'LaunchDarkly', ARRAY['launchdarkly.com']::text[]),
('localsearch', 'Localsearch', ARRAY['localsearch.com.au']::text[]),
('magnite', 'Magnite', ARRAY['magnite.com']::text[]),
('mckinsey_company', 'McKinsey & Company', ARRAY['external.mckinsey.com','finalta-global.com','iguazio.com','mckinsey.com']::text[]),
('merative', 'Merative', ARRAY['merative.com']::text[]),
('merge', 'MERGE', ARRAY['mergeworld.com']::text[]),
('mews', 'Mews', ARRAY['mews.com']::text[]),
('miro', 'Miro', ARRAY['miro.com']::text[]),
('modsquad', 'ModSquad', ARRAY['modsquad.com']::text[]),
('msci_inc', 'MSCI Inc.', ARRAY['msci.com']::text[]),
('msi_reproductive_choices', 'MSI Reproductive Choices', ARRAY['msichoices.org','msichoices.org.ng']::text[]),
('nasdaq', 'Nasdaq', ARRAY['nasdaq.com']::text[]),
('natura', 'Natura', ARRAY['natura.net']::text[]),
('nebius', 'Nebius', ARRAY['nebius.com']::text[]),
('nemetschek', 'Nemetschek', ARRAY['123erfasst.de','allplan.com','bluebeam.com','crem-solutions.de','devicemagic.com','drofus.com','gocanvas.com','graphisoft.com','graphisoft.de','maxon.net','nemetschek.bg','nemetschek.blue','nemetschek.com','nevaris.com','risa.com','sitedocs.com','solibri.com','spacewell.com','vectorworks.net','vectorworks.net.au']::text[]),
('novo_holdings', 'Novo Holdings', ARRAY['novo.dk']::text[]),
('nursa', 'Nursa', ARRAY['nursa.com']::text[]),
('nvidia', 'Nvidia', ARRAY['nvidia.com']::text[]),
('observeai', 'Observe.AI', ARRAY['observe.ai']::text[]),
('okta', 'Okta', ARRAY['okta.com']::text[]),
('olx', 'OLX', ARRAY['autotrader.co.za','olx.bg','olx.com','olx.com.br','olx.kz','olx.pl','olx.pt','olx.ro','olx.uz','otodom.pl','otomoto.pl','property24.com']::text[]),
('oura_health', 'Oura Health', ARRAY['ouraring.com']::text[]),
('paf', 'Paf', ARRAY['paf.com']::text[]),
('palo_alto_networks', 'Palo Alto Networks', ARRAY['paloaltonetworks.com']::text[]),
('paymentology', 'Paymentology', ARRAY['paymentology.com']::text[]),
('paynearme', 'PayNearMe', ARRAY['paynearme.com']::text[]),
('payoneer', 'Payoneer', ARRAY['payoneer.com']::text[]),
('paz_retail_energy', 'Paz Retail & Energy', ARRAY['paz.co.il','pazgas.co.il','www.paz.co.il']::text[]),
('pendo', 'Pendo', ARRAY['pendo.io']::text[]),
('pennylane', 'Pennylane', ARRAY['pennylane.com']::text[]),
('perficient', 'Perficient', ARRAY['perficient.com']::text[]),
('permobil', 'Permobil', ARRAY['permobil.com']::text[]),
('phi_aviation', 'PHI Aviation', ARRAY['phiairmedical.com','phihelico.com']::text[]),
('pipedrive', 'Pipedrive', ARRAY['partner.pipedrive.com']::text[]),
('portswigger', 'Portswigger', ARRAY['portswigger.net']::text[]),
('project44', 'Project44', ARRAY['project44.com']::text[]),
('quarterhill_inc', 'Quarterhill Inc.', ARRAY['quarterhill.com']::text[]),
('raintree_systems', 'Raintree Systems', ARRAY['raintreeinc.com']::text[]),
('rd_saude', 'RD Saude', ARRAY['rd.com.br','rdsaude.com.br']::text[]),
('remote', 'Remote', ARRAY['remote.com']::text[]),
('retal', 'Retal', ARRAY['retal.com.sa']::text[]),
('root_inc', 'Root Inc.', ARRAY['joinroot.com']::text[]),
('royal_caribbean_international', 'Royal Caribbean International', ARRAY['celebrity.com','rccl.com','rcclapac.com','silversea.com']::text[]),
('sage', 'Sage', ARRAY['sage.com']::text[]),
('sarnova', 'Sarnova', ARRAY['cardiopartners.com','sarnova.com']::text[]),
('sequencing', 'Sequencing', ARRAY['sequencing.com']::text[]),
('shipt', 'Shipt', ARRAY['shipt.com']::text[]),
('shv_energy', 'SHV Energy', ARRAY['calor.co.uk','shvenergy.com']::text[]),
('silverfort', 'Silverfort', ARRAY['silverfort.com']::text[]),
('sinch', 'Sinch', ARRAY['sinch.com']::text[]),
('smartsheet', 'Smartsheet', ARRAY['smartsheet.com']::text[]),
('spiraledge', 'Spiraledge', ARRAY['spiraledge.com']::text[]),
('spotify', 'Spotify', ARRAY['spotify.com']::text[]),
('squarespace', 'Squarespace', ARRAY['squarespace.com']::text[]),
('stanley_black_decker_inc', 'Stanley Black & Decker, Inc.', ARRAY['sbdinc.com']::text[]),
('stellar_gaming', 'Stellar Gaming', ARRAY['estrelabet.com','stellargaming.com']::text[]),
('success_academy', 'Success Academy', ARRAY['saschools.org','successacademies.org']::text[]),
('sylvera', 'Sylvera', ARRAY['sylvera.io']::text[]),
('taxfix', 'Taxfix', ARRAY['taxfix.com','taxfix.de','taxfix.es']::text[]),
('teleperformance', 'Teleperformance', ARRAY['majorel.com','mj.teleperformance.com','teleperformance.com','teleperformance.onmicrosoft.com','tp.com']::text[]),
('the_advantage_co', 'The Advantage Co.', ARRAY['theadvantage.com']::text[]),
('the_carlyle_group', 'The Carlyle Group', ARRAY['carlyle.com']::text[]),
('the_college_board', 'The College Board', ARRAY['collegeboard.org']::text[]),
('the_scion_group', 'The Scion Group', ARRAY['thesciongroup.com']::text[]),
('tide', 'Tide', ARRAY['tide.co']::text[]),
('triton_partners', 'Triton Partners', ARRAY['aips.triton-partners.com','triton-partners.com']::text[]),
('twilio', 'Twilio', ARRAY['twilio.com']::text[]),
('uber', 'Uber', ARRAY['ext.uber.com','uber.com']::text[]),
('udacity', 'Udacity', ARRAY['udacity.com']::text[]),
('veed', 'VEED', ARRAY['veed.io']::text[]),
('vinted', 'Vinted', ARRAY['vinted.com']::text[]),
('vivun', 'Vivun', ARRAY['vivun.com']::text[]),
('white_label_md', 'White Label MD', ARRAY['whitelabelmd.com']::text[]),
('workleap', 'Workleap', ARRAY['workleap.com']::text[]),
('zendesk', 'Zendesk', ARRAY['zendesk.com']::text[]),
('zeta_global', 'Zeta Global', ARRAY['zetaglobal.com']::text[]),
('zs', 'ZS', ARRAY['zs.com']::text[])
ON CONFLICT (account_key) DO NOTHING;
ALTER TABLE public.v3_customer_accounts ENABLE TRIGGER v3_customer_accounts_domain_collision;
COMMIT;